export const LP_GRID_ITEMS = [
  {
    id: 1,
    title: "Brochure",
    data: [
      {
        id: 1,
        title: "Syrincs Brochure ",
        slug: "Brochure",
        lang: "cn",
        type: "brochure",
        filename: "download/syrincs_brochure.pdf",
      },
      {
        id: 2,
        title: "Syrincs Brochure 2",
        slug: "Brochure 2",
        lang: "cn",
        type: "brochure",
        filename: "download/syrincs_brochure2.pdf",
      },
    ],
  },
  {
    id: 2,
    title: "PTK",
    data: [
      {
        id: 21,
        title: "Syrincs PTK1 Manual",
        slug: "PTK1",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_ptk1_manual.pdf",
      },
      {
        id: 22,
        title: "Syrincs SUB21 Manual",
        slug: "SUB21",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_sub21_manual.pdf",
      },
    ],
  },
  {
    id: 3,
    title: "SH",
    data: [
      {
        id: 31,
        title: "Syrincs SH221B Manual",
        slug: "SH221B",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_sh221b_manual.pdf",
      },
      {
        id: 32,
        title: "Syrincs SH218B II Manual",
        slug: "SH218BII",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_sh218bii_manual.pdf",
      },
      {
        id: 33,
        title: "Syrincs SH215B Manual",
        slug: "SH215B",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_sh215b_manual.pdf",
      },
      {
        id: 34,
        title: "Syrincs SH212M II Manual",
        slug: "SH212MII",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_sh212mii_manual.pdf",
      },
      {
        id: 35,
        title: "Syrincs SH210H II Manual",
        slug: "SH210HII",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_sh210hii_manual.pdf",
      },
      {
        id: 36,
        title: "Syrincs SH112F II Manual",
        slug: "SH112FII",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_sh112fii_manual.pdf",
      },
      {
        id: 37,
        title: "Syrincs SH402H Manual",
        slug: "SH402H",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_sh402h_manual.pdf",
      },
    ],
  },
  {
    id: 4,
    title: "ZERO",
    data: [
      {
        id: 41,
        title: "Syrincs ZERO100 Manual",
        slug: "ZERO100",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_zero100_manual.pdf",
      },
      {
        id: 42,
        title: "Syrincs ZERO120 Manual",
        slug: "ZERO120",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_zero120_manual.pdf",
      },
      {
        id: 43,
        title: "Syrincs ZERO122 Manual",
        slug: "ZERO122",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_zero122_manual.pdf",
      },
    ],
  },
  {
    id: 5,
    title: "CK",
    data: [
      {
        id: 51,
        title: "Syrincs CK-12 Manual",
        slug: "CK-12",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_ck-12_manual.pdf",
      },
      {
        id: 52,
        title: "Syrincs CK-14 Manual",
        slug: "CK-14",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_ck-14_manual.pdf",
      },
      {
        id: 53,
        title: "Syrincs CK120 Manual",
        slug: "CK120",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_ck120_manual.pdf",
      },
      {
        id: 54,
        title: "Syrincs CK130 Manual",
        slug: "CK130",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_ck130_manual.pdf",
      },
    ],
  },
  {
    id: 5,
    title: "DS",
    data: [
      {
        id: 51,
        title: "Syrincs DS135 Manual",
        slug: "ds135",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_ds135_manual.pdf",
      },
      {
        id: 52,
        title: "Syrincs DS136 Manual",
        slug: "ds136",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_ds136_manual.pdf",
      },
    ],
  },
  {
    id: 6,
    title: "Live Close",
    data: [
      {
        id: 61,
        title: "Syrincs LIVE CLOSE312 Manual",
        slug: "LIVE CLOSE312",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_live_close312_manual.pdf",
      },
      {
        id: 62,
        title: "Syrincs LIVE CLOSE15S Manual",
        slug: "LIVE CLOSE15S",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_live_close15s_manual.pdf",
      },
      {
        id: 63,
        title: "Syrincs LIVE CLOSE15B Manual",
        slug: "LIVE CLOSE15B",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_live_close15b_manual.pdf",
      },
      {
        id: 64,
        title: "Syrincs LIVE CLOSE18B Manual",
        slug: "LIVE CLOSE18B",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_live_close18b_manual.pdf",
      },
      // {
      //   id: 23,
      //   title: "Syrincs LIVE CLOSE18B II Manual",
      //   slug: "LIVE CLOSE18B II",
      //   lang: "cn",
      //   type: "manual",
      //   filename: "download/syrincs_live_close18bii_manual.pdf",
      // },
      {
        id: 65,
        title: "Syrincs LIVE CLOSE21B Manual",
        slug: "LIVE CLOSE21B",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_live_close21b_manual.pdf",
      },
      {
        id: 66,
        title: "Syrincs LIVE CLOSE218B Manual",
        slug: "LIVE CLOSE218B",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_live_close218b_manual.pdf",
      },
      // {
      //   id: 25,
      //   title: "Syrincs LIVE CLOSE218B II Manual",
      //   slug: "LIVE CLOSE218B II",
      //   lang: "cn",
      //   type: "manual",
      //   filename: "download/syrincs_live_close218bii_manual.pdf",
      // },
    ],
  },
  {
    id: 7,
    title: "FOCUS",
    data: [
      {
        id: 71,
        title: "Syrincs FOCUS100 Manual",
        slug: "FOCUS100",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_focus100_manual.pdf",
      },
      {
        id: 72,
        title: "Syrincs FOCUS120E Manual",
        slug: "FOCUS120E",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_focus120e_manual.pdf",
      },
      {
        id: 73,
        title: "Syrincs FOCUS120 Manual",
        slug: "FOCUS120",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_focus120_manual.pdf",
      },
      {
        id: 74,
        title: "Syrincs FOCUS133 Manual",
        slug: "FOCUS133",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_focus133_manual.pdf",
      },
    ],
  },
  {
    id: 8,
    title: "CLUB",
    data: [
      {
        id: 81,
        title: "Syrincs CLUB18W Manual",
        slug: "CLUB18W",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_club18w_manual.pdf",
      },
    ],
  },
  {
    id: 9,
    title: "RULE",
    data: [
      {
        id: 91,
        title: "Syrincs RULE10 Manual",
        slug: "RULE10",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_rule10_manual.pdf",
      },
      {
        id: 92,
        title: "Syrincs RULE12_RULE12UK Manual",
        slug: "RULE12 RULE12UK",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_rule12_rule12uk_manual.pdf",
      },
      {
        id: 93,
        title: "Syrincs RULE13.3 Manual",
        slug: "RULE13.3",
        lang: "cn",
        filename: "download/syrincs_rule13.3_manual.pdf",
      },
      {
        id: 94,
        title: "Syrincs RULE18 Manual",
        slug: "RULE18",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_rule18_manual.pdf",
      },
      {
        id: 95,
        title: "Syrincs RULE18W Manual",
        slug: "RULE18W",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_rule18w_manual.pdf",
      },
    ],
  },
  {
    id: 10,
    title: "MJ",
    data: [
      {
        id: 101,
        title: "Syrincs MJ12M Manual",
        slug: "MJ12M",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_mj12m_manual.pdf",
      },
    ],
  },
  {
    id: 11,
    title: "Amplifier",
    data: [
      {
        id: 111,
        title: "Syrincs G Manual",
        slug: "G",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_g_manual.pdf",
      },
      {
        id: 112,
        title: "Syrincs THINK5.2 Manual",
        slug: "THINK5.2",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_think52_manual.pdf",
      },
      {
        id: 113,
        title: "Syrincs THINK5.4 Manual",
        slug: "THINK5.4",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_think54_manual.pdf",
      },
      {
        id: 114,
        title: "Syrincs DX4.12 Manual",
        slug: "DX4.12",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_dx4.12_manual.pdf",
      },
    ],
  },
  {
    id: 12,
    title: "Electronic",
    data: [
      {
        id: 121,
        title: "Syrincs D-Macth Manual",
        slug: "D-Macth",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_d_macth_manual.pdf",
      },
      {
        id: 122,
        title: "Syrincs D-Quick2 Manual",
        slug: "D-Quick2",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_d-quick2_manual.pdf",
      },
      {
        id: 123,
        title: "Syrincs VE06 Manual",
        slug: "VE06",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_ve06_manual.pdf",
      },
      {
        id: 124,
        title: "Syrincs VE08 Manual",
        slug: "VE08",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_ve08_manual.pdf",
      },
      {
        id: 125,
        title: "Syrincs GP820 Manual",
        slug: "GP820",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_gp820_manual.pdf",
      },
    ],
  },
  {
    id: 13,
    title: "Microphone",
    data: [
      {
        id: 131,
        title: "Syrincs WM3 Manual",
        slug: "WM3",
        lang: "cn",
        type: "manual",
        filename: "download/syrincs_wm3_manual.pdf",
      },
    ],
  },
  {
    id: 14,
    title: "Soft",
    data: [
      {
        id: 141,
        title: "Syrincs Dmatch Soft",
        slug: "dmatch",
        lang: "cn",
        type: "soft",
        filename: "soft/dmatch.rar",
      },
      {
        id: 142,
        title: "Syrincs VE06 Soft",
        slug: "ve06",
        lang: "cn",
        type: "soft",
        filename: "soft/VE06.rar",
      },
      {
        id: 143,
        title: "Syrincs AudioController Soft",
        slug: "AudioController",
        lang: "cn",
        type: "soft",
        filename: "soft/AudioController.zip",
      },
    ],
  },
];
