title: liveclose 18B
ctitle: 18寸高声压低音炮
description: 频率响应 (-3dB) 33Hz-130Hz | 额定功率 (RMS) 500W | 灵敏度（ 1W@1M ）97dB | 最大声压级 130dB/136dB (peak)
image: /images/products/liveclose18b/liveclose18b-0.jpg
dimensional: /images/products/liveclose18b/liveclose18b-dimensions.png
images:
  [
    "/images/products/liveclose18b/liveclose18b-1.jpg",
    "/images/products/liveclose18b/liveclose18b-2.jpg",
    "/images/products/liveclose18b/liveclose18b-3.jpg",
    "/images/products/liveclose18b/liveclose18b-4.jpg",
    "/images/products/liveclose18b/liveclose18b-5.jpg",
    "/images/products/liveclose18b/liveclose18b-6.jpg",
    "/images/products/liveclose18b/liveclose18b-7.jpg",
  ]
category: speaker
slug: liveclose18b
language: zh
date: 2024-03-03
features:
  [
    "18英寸低频的组合提供了高保真的音效。",
    "额定功率500W，最大可以达到2000W，满足各种场景的需求。",
    "21mm层压板箱配铁网，坚固耐用。",
    "配备NL4连接件及升降套件，可灵活适应各种场景。",
    "价格合理，性能优异，物有所值。",
  ]
content:
  liveclose 18B是一款专门为追求高品质声音输出的用户设计的低音炮，箱体采用烤漆木质材质，既保证了音箱的美观度，又拥有良好的声学表现。

  liveclose 18B凭借出色的性能、优质的用料、精致的设计，无论是在专业音响领域还是日常娱乐场景，都能为用户带来极佳的声音体验。

technicalspecification: [
    { name: "频率响应(-3db)", value: "33Hz-130Hz" },
    { name: "额定功率(RMS)", value: "500W" },
    # { name: "Total Power(MUSIC)", value: "1000W" },
    # { name: "Total Power(PEAK)", value: "2000W" },
    { name: "最大声压级 @ 1m", value: "130dB/136dB (PEAK)" },
    { name: "灵敏度 1W @ 1m", value: "97 dB" },
    { name: "额定阻抗 (Ohm)", value: "8 Ω" },
  ]

physicalspecification:
  [
    { name: "音箱", value: "18英寸低音炮" },
    { name: "低音扬声器", value: "1 x 18 英寸低频单元" },
    { name: "箱体材质", value: "21mm 层压板" },
    { name: "箱体材质", value: "水性煤灰色沙面漆" },
    { name: "面网", value: "喷粉涂层" },
    { name: "连接器", value: "2 x NL4" },
    { name: "可选配件", value: "吊装套件" },
    { name: "尺寸(W x D x H)", value: "700 × 683 × 655mm" },
    { name: "包装尺寸(W x D x H):", value: "809 × 768 × 762mm" },
    { name: "净重", value: "45kg" },
    { name: "毛重", value: "48kg" },
  ]
downloads: [
    {
      title: "照片",
      url: "/images/products/liveclose18b/liveclose18b-0.jpg",
      icon: "/images/jpg.gif",
    },
    {
      title: "说明书",
      url: "/download/syrincs_live_close18b_说明书.pdf",
      icon: "/images/pdf.gif",
    },
    # { title: "Dimensional drawing", url: "", icon: "/images/pdf.gif" },
    # { title: "Software", url: "", icon: "/images/unknown.gif" },
  ]
# | Specification parameters     |                            |
# | ---------------------------- | -------------------------- |
# | Box                          | 15mm层压板       |
# | Unit Composition Transformer | 1 x 18 "Low Frequency Unit |
# | 频率响应 (-3dB)    | 33Hz-130Hz                 |
# | 额定功率 (RMS)            | 500W                       |
# | 灵敏度（ 1W@1M )        | 97dB                       |
# | Maximum SPL                  | 130dB/136dB (peak)         |
# | Rated Impedance              | 8 OHM                      |
# | 尺寸 (W × D × H)       | 700 × 655 × 683mm          |
# | Package Dimension            | 768 × 762 × 809mm          |
# | 净重                   | 45Kg                       |
# | 毛重                 | 48Kg                       |
