title: ZERO100
ctitle: 10 英寸双向全频扬声器
description: 频率响应 65Hz-18kHz (-3dB) | 额定功率 RMS 300W | 灵敏度 94 dB
image: /images/products/zero100/zero100-0.jpg
dimensional: /images/products/zero100/zero100-dimensions.png
images:
  [
    "/images/products/zero100/zero100-1.jpg",
    "/images/products/zero100/zero100-2.jpg",
    "/images/products/zero100/zero100-3.jpg",
    "/images/products/zero100/zero100-4.jpg",
    "/images/products/zero100/zero100-5.jpg",
    "/images/products/zero100/zero100-6.jpg",
  ]
category: speaker
slug: zero100
language: zh
date: 2024-01-04

features:
  [
    "10英寸低频和1.75英寸高频单元的组合，提供了高保真的音效。",
    "额定功率300W，最大可达1200W，满足各类场景需求。",
    "15mm层压板箱配铁网，坚固耐用。",
    "配备NL4连接件及升降套件，可灵活适应各种场景。",
    "价格合理，性能优异，物有所值。",
  ]
content:
  ZERO100是一款专为追求高品质声音输出的用户设计的全频音箱。箱体采用烤漆木质材质，既保证了音箱的美观度，又拥有良好的声学表现。

  ZERO100凭借出色的性能、优质的用料、精致的设计，无论是在专业音响领域还是日常娱乐场景，都能为用户带来极佳的声音体验。

technicalspecification: [
    { name: "频率响应(-3db)", value: "65Hz-18kHz" },
    # { name: "频率响应(-10db)", value: "60Hz-20kHz" },
    { name: "额定功率(RMS)", value: "300W" },
    # { name: "Total Power(MUSIC)", value: "600W" },
    # { name: "Total Power(PEAK)", value: "1200W" },
    { name: "最大声压级 @ 1m", value: "120dB/126dB (PEAK)" },
    { name: "指向性 (H x V)", value: "110 x 120" },
    { name: "灵敏度 1W @ 1m", value: "94 dB" },
    { name: "额定阻抗 (Ohm)", value: "8 Ω" },
    # { name: "Crossover Frequencies", value: "2.3kHz" },
    # { name: "Distortion 10% P", value: "≤5%" },
  ]

physicalspecification:
  [
    { name: "音箱", value: "10 寸2分频全频扬声器" },
    { name: "低音扬声器", value: "1 x 10 寸低频单元" },
    { name: "压缩驱动器", value: "1 x 34-core 压缩驱动器" },
    { name: "分频模式", value: "内置二路分频器" },
    { name: "箱体材质", value: "12mm 层压板" },
    { name: "箱体材质", value: "水性煤灰色沙面漆" },
    { name: "面网", value: "静电粉末喷涂黑色细砂哑光,1.2mm低碳钢" },
    { name: "连接器", value: "2 x NL4" },
    { name: "可选配件", value: "吊装套件" },
    { name: "尺寸(W x D x H)", value: "298 × 382 × 540mm" },
    { name: "包装尺寸(W x D x H):", value: "365 × 465 × 640mm" },
    { name: "净重", value: "15kg" },
    { name: "毛重", value: "17kg" },
  ]
downloads: [
    {
      title: "照片",
      url: "/images/products/zero100/zero100-0.jpg",
      icon: "/images/jpg.gif",
    },
    {
      title: "说明书",
      url: "/download/syrincs_zero100_说明书.pdf",
      icon: "/images/pdf.gif",
    },
    # { title: "Dimensional drawing", url: "", icon: "/images/pdf.gif" },
    # { title: "Software", url: "", icon: "/images/unknown.gif" },
  ]
# | Specification parameters       |                                                                                      |
# | ------------------------------ | ------------------------------------------------------------------------------------ |
# | System Type                    | Bass Reflective Design                                                               |
# | Unit composition               | LF: 10 inches, 65 cores, 300W AES HF: 44 cores, 100W AES polymer composite diaphragm |
# | 分频模式        | 内置二路分频器                                                   |
# | 频率响应             | 70Hz-18kHz (-3dB)                                                                    |
# | 频率响应             | 60Hz-20kHz (-10dB)                                                                   |
# | 额定功率 AES                | 300W                                                                                 |
# | Long term maximum power        | 600W                                                                                 |
# | Short term maximum power       | 1200W                                                                                |
# | Frequency division point       | 2.3kHz                                                                               |
# | 灵敏度                    | 94 dB                                                                                |
# | Maximum sound pressure level   | 120dB/126dB (peak)                                                                   |
# | Effective sound pressure level | 105dB/111dB (peak)                                                                   |
# | Impedance                      | 8 Ω                                                                                  |
# | Installation                   | Top and Side Lifting Points                                                          |
# | Box                            | 15mm层压板                                                                 |
# | 箱体材质          | 水性煤灰色沙面漆                                             |
# | Iron mesh                      | 静电粉末喷涂黑色细砂哑光,1.2mm低碳钢           |
# | 连接器                      | 2 × NL4                                                                              |
# | 可选配件           | 吊装套件                                                                          |
# | 尺寸 (W × D × H)         | 300 × 381 × 540mm                                                                    |
# | Packaging size                 | 365 × 465 × 640mm                                                                    |
# | 净重                     | 15.00kg                                                                              |
# | 毛重                   | 17.00kg                                                                              |
