title: FOCUS120
ctitle: 12寸两分频全频扬声器
description: 频率响应 55Hz-20kHz (-3dB) | 额定功率 RMS 400W | 灵敏度 97.5 dB
image: /images/products/focus120/focus120-0.jpg
dimensional: /images/products/focus120/focus120-dimensions.png
images:
  [
    "/images/products/focus120/focus120-1.jpg",
    "/images/products/focus120/focus120-2.jpg",
    "/images/products/focus120/focus120-3.jpg",
    "/images/products/focus120/focus120-4.jpg",
    "/images/products/focus120/focus120-5.jpg",
    "/images/products/focus120/focus120-6.jpg",
  ]
category: speaker
slug: focus120
language: zh
date: 2024-01-02

features:
  [
    "12英寸低频和1.75英寸高频单元的组合，提供了高保真的音效。",
    "额定功率400W，最大可达1600W，满足各类场景需求。",
    "15mm层压板箱配铁网，坚固耐用。",
    "配备NL4连接件及升降套件，可灵活适应各种场景。",
    "价格合理，性能优异，物有所值。",
  ]
content:
  FOCUS120是一款专为追求高品质声音输出的用户设计的全频音箱。箱体采用烤漆木质材质，既保证了音箱的美观度，又拥有良好的声学表现。

  FOCUS120凭借出色的性能、优质的用料、精致的设计，无论是在专业音响领域还是日常娱乐场景，都能为用户带来极佳的声音体验。

technicalspecification: [
    { name: "频率响应(-3db)", value: "55Hz-20kHz" },
    # { name: "频率响应(-10db)", value: "45Hz-20kHz" },
    { name: "额定功率(AES)", value: "400W" },
    # { name: "Total Power(MUSIC)", value: "800W" },
    # { name: "Total Power(PEAK)", value: "1600W" },
    { name: "最大声压级 @ 1m", value: "125dB/131dB (PEAK)" },
    { name: "指向性 (H x V)", value: "90 x 95" },
    { name: "灵敏度 1W @ 1m", value: "97.5 dB" },
    { name: "额定阻抗 (Ohm)", value: "8 Ω" },
    # { name: "Crossover Frequencies", value: "2.2kHz" },
    # { name: "Distortion 10% P", value: "≤5%" },
  ]

physicalspecification:
  [
    { name: "音箱", value: "12 寸2分频全频扬声器" },
    { name: "低音扬声器", value: "1 x 12 寸低频单元" },
    { name: "压缩驱动器", value: "1 x 44 芯压缩驱动器" },
    { name: "分频模式", value: "内置二路分频器" },
    { name: "箱体材质", value: "15mm层压板" },
    { name: "箱体材质", value: "水性煤灰色沙面漆" },
    { name: "面网", value: "静电粉末喷涂黑色细砂哑光,1.2mm低碳钢" },
    { name: "连接器", value: "2 x NL4" },
    { name: "可选配件", value: "吊装套件" },
    { name: "尺寸(W x D x H)", value: "343 x 439 x 600mm" },
    { name: "包装尺寸(W x D x H):", value: "396 x 478 x 640mm" },
    { name: "净重", value: "22.7kg" },
    { name: "毛重", value: "24.8kg" },
  ]
downloads: [
    {
      title: "照片",
      url: "/images/products/focus120/focus120-0.jpg",
      icon: "/images/jpg.gif",
    },
    {
      title: "说明书",
      url: "/download/syrincs_focus120_说明书.pdf",
      icon: "/images/pdf.gif",
    },
    # { title: "Dimensional drawing", url: "", icon: "/images/pdf.gif" },
    # { title: "Software", url: "", icon: "/images/unknown.gif" },
  ]
# | Specification parameters                  |                                                                            |
# | ----------------------------------------- | -------------------------------------------------------------------------- |
# | Box                                       | Painted Wooden Full Range Speaker                                          |
# | Unit composition                          | 1 x 12 "low-frequency unit 1 x 1.7" high-frequency driver                  |
# | 分频模式                   | 内置二路分频器                                         |
# | 频率响应 (-3dB)                 | 55Hz-20kHz                                                                 |
# | 频率响应 (-3dB)                 | 45Hz-20kHz                                                                 |
# | 额定功率 AES                           | 400W                                                                       |
# | Long term maximum power                   | 800W                                                                       |
# | Short term maximum power                  | 1600W                                                                      |
# | Distortion 10% P                          | ≤5%                                                                        |
# | 灵敏度                               | 97.5 dB                                                                    |
# | Maximum sound pressure level pink noise   | 125dB/131dB (peak)                                                         |
# | Effective sound pressure level pink noise | 116dB/122dB (peak)                                                         |
# | Impedance                                 | 8 Ω                                                                        |
# | Box                                       | 15mm层压板                                                       |
# | 箱体材质                     | Coal gray water-based sand surface paint spraying                          |
# | Iron mesh                                 | 静电粉末喷涂黑色细砂哑光,1.2mm低碳钢 |
# | 连接器                                 | 2 × NL4                                                                    |
# | 可选配件                      | 吊装套件                                                                |
# | 尺寸 (W × D × H)                    | 352 × 600 × 450 mm                                                         |
# | Weight                                    | 22.7kg                                                                     |
