title: MJ12M
ctitle: Built in 2-channel 12 inch coaxial point sound source full frequency speaker
description: Frequency response (-3dB):58Hz-20KHz | Rated power:400W | Maximum sound pressure level:124dB/130dB
image: /images/products/mj12m/mj12m-0.jpg
dimensional: /images/products/mj12m/mj12m-dimensions.png
images:
  [
    "/images/products/mj12m/mj12m-1.jpg",
    "/images/products/mj12m/mj12m-2.jpg",
    "/images/products/mj12m/mj12m-3.jpg",
    "/images/products/mj12m/mj12m-4.jpg",
    "/images/products/mj12m/mj12m-5.jpg",
  ]
category: speaker
slug: mj12m
date: 2024-04-01

features:
  [
    "The combination of 12 inch low-frequency and 1.75-inch high-frequency units provides high fidelity sound effects.",
    "The rated power is 400W, and the maximum can reach 1600W, meeting the needs of various scenarios.",
    "18mm laminated board box with iron mesh, sturdy and durable.",
    "Equipped with NL4 connectors and lifting kits, it can flexibly adapt to various scenarios.",
    "Reasonable price, excellent performance, and value for money.",
  ]
content:
  Multi angle compact structural design, with two fixed angles of 30 ° and 60 °, can be used as the main or auxiliary distributed sound reinforcement, and can also be used as a replay. 12 inch 75 core neodymium magnet design, with a 44 core coaxial installation on the back of the bass for high frequencies, sharing the same neodymium magnet with the bass for efficient and exquisite design.

  -Designed primarily for large and medium-sized performing arts, bars, theaters, live performances, and other venues, the surround sound system is designed to provide audio feedback;
  -Cooperate with MJ1023, MJ1022 or MJ1239 to form a system;
  -Paired with the bass CLUB18W, it can extend the low frequency to 40Hz;
  -High sound pressure level and high-definition design.

technicalspecification: [
    { name: "Frequency Response(-3db)", value: "58Hz-20kHz" },
    # { name: "Frequency Response(-10db)", value: "50Hz-20kHz" },
    { name: "Rated Power(RMS)", value: "400W" },
    # { name: "Total Power(MUSIC)", value: "800W" },
    # { name: "Total Power(PEAK)", value: "1600W" },
    { name: "Max SPL @ 1m", value: "124dB/130dB (PEAK)" },
    { name: "Dispersion (H x V)", value: "120 x 120" },
    { name: "Sensitivity 1W @ 1m", value: "97 dB" },
    { name: "Nominal Impedance (Ohm)", value: "8 Ω" },
    # { name: "Crossover Frequencies", value: "2.3kHz" },
    # { name: "Distortion 10% P", value: "≤5%" },
  ]

physicalspecification:
  [
    { name: "Box", value: "12 inch Two Way Full Range Speaker" },
    { name: "Woofer", value: "1 x 12 inch low-frequency unit" },
    {
      name: "Compression driver",
      value: "1 x 1.75 inch high-frequency driver",
    },
    {
      name: "Frequency division mode",
      value: "Built in two-way frequency divider",
    },
    { name: "Cabinet/Case Material", value: "18mm laminated board" },
    {
      name: "Box surface treatment",
      value: "Water based coal grey sand surface paint",
    },
    {
      name: "Grille",
      value: "Electrostatic powder coating black fine sand matte, 1.2mm low carbon steel",
    },
    { name: "Connector", value: "2 x NL4" },
    { name: "Optional Accessories", value: "Lifting kit" },
    { name: "Dimensions(W x D x H)", value: "540 × 430 × 377mm" },
    { name: "Package Dimensions(W x D x H):", value: "660 × 525 × 460mm" },
    { name: "Net weight", value: "15.8kg" },
    { name: "Gross weight", value: "18.3kg" },
  ]
downloads: [
    {
      title: "Hi-res photo",
      url: "/images/products/mj12m/mj12m-0.jpg",
      icon: "/images/jpg.gif",
    },
    {
      title: "Manual",
      url: "/download/Syrincs_mj12m_manual.pdf",
      icon: "/images/pdf.gif",
    },
    # { title: "Dimensional drawing", url: "", icon: "/images/pdf.gif" },
    # { title: "Software", url: "", icon: "/images/unknown.gif" },
  ]
# | Specification parameters       |                                                                                                  |
# | ------------------------------ | ------------------------------------------------------------------------------------------------ |
# | Box Construction               | 18mm laminated board surface with water-based coal grey sand paint                               |
# | Unit composition Transformer   | 1 x 12 "low-frequency neodymium magnetic unit 1 x 1.73" neodymium magnetic high-frequency driver |
# | Frequency Response (-3dB)      | 58Hz-20KHz                                                                                       |
# | Rated Power (AES)              | 400W                                                                                             |
# | Sensitivity（ 1W@1M )          | 97dB                                                                                             |
# | Maximum SPL                    | 124dB/130dB (peak)                                                                               |
# | Rated Impedance                | 8 OHM                                                                                            |
# | Directional Dispersion (H × V) | 120 °× 120 °                                                                                     |
# | Dimensions (W × D × H)         | 540mmx430mmx365mm                                                                                |
# | Package Dimension              | 660mmx525mmx460mm                                                                                |
# | Net Weight                     | 15.7KG                                                                                           |
# | Gross Weight                   | 18.25KG                                                                                          |
