title: LiveClose 15S
ctitle: 15 inch high sound pressure front directional speaker
description: Frequency response 50Hz-18kHz (-3dB) | 45Hz-20kHz (-10dB) | Rated power AES 750W | Sensitivity 99 dB
image: /images/products/liveclose15s/liveclose15s-0.jpg
dimensional: /images/products/focus100/focus100-dimensions.jpg
images:
  [
    "/images/products/liveclose15s/liveclose15s-1.jpg",
    "/images/products/liveclose15s/liveclose15s-2.jpg",
    "/images/products/liveclose15s/liveclose15s-3.jpg",
    "/images/products/liveclose15s/liveclose15s-4.jpg",
    "/images/products/liveclose15s/liveclose15s-5.jpg",
    "/images/products/liveclose15s/liveclose15s-6.jpg",
    "/images/products/liveclose15s/liveclose15s-7.jpg",
    "/images/products/liveclose15s/liveclose15s-8.jpg",
    "/images/products/liveclose15s/liveclose15s-9.jpg",
  ]
category: speaker
slug: liveclose15s
date: 2024-03-01

features:
  [
    "The combination of 15 inch low-frequency and 1.7-inch high-frequency units provides high fidelity sound effects.",
    "The rated power is 750W, and the maximum can reach 3000W, meeting the needs of various scenarios.",
    "15mm laminated board box with iron mesh, sturdy and durable.",
    "Equipped with NL4 connectors and lifting kits, it can flexibly adapt to various scenarios.",
    "Reasonable price, excellent performance, and value for money.",
  ]
content:
  LiveClose 15S is a full range speaker designed specifically for users who pursue high-quality sound output. The box body is made of baked paint wood material, which not only ensures the beauty of the speaker, but also has good acoustic performance.

  LiveClose 15S, with its outstanding performance, high-quality materials, and exquisite design, can bring users an excellent sound experience in both professional audio fields and daily entertainment scenarios.

technicalspecification:
  [
    { name: "Frequency Response(-3db)", value: "50Hz-18kHz" },
    { name: "Frequency Response(-10db)", value: "45Hz-20kHz" },
    { name: "Rated Power(AES)", value: "750W" },
    { name: "Total Power(MUSIC)", value: "1500W" },
    { name: "Total Power(PEAK)", value: "3000W" },
    { name: "Max SPL @ 1m", value: "127dB/133dB (PEAK)" },
    { name: "Dispersion (H x V)", value: "90 x 95" },
    { name: "Sensitivity 1W @ 1m", value: "99 dB" },
    { name: "Nominal Impedance (Ohm)", value: "8 Ω" },
    { name: "Crossover Frequencies", value: "2.2kHz" },
    { name: "Distortion 10% P", value: "≤5%" },
  ]

physicalspecification:
  [
    { name: "Box", value: "14 inch Two Way Full Range Speaker" },
    { name: "Woofer", value: "1 x 14 'low-frequency unit" },
    { name: "Compression driver", value: "1 x 1.7' high-frequency driver" },
    {
      name: "Frequency division mode",
      value: "Built in two-way frequency divider",
    },
    { name: "Cabinet/Case Material", value: "15mm+18mm laminated board" },
    {
      name: "Box surface treatment",
      value: "Water based coal grey sand surface paint",
    },
    {
      name: "Grille",
      value: "Electrostatic powder coating black fine sand matte, 1.2mm low carbon steel",
    },
    { name: "Connector", value: "2 x NL4" },
    { name: "Optional Accessories", value: "Lifting kit" },
    { name: "Dimensions(W x D x H)", value: "385 × 645 × 450 mm" },
    { name: "Package Dimensions(W x D x H):", value: "465 × 573 × 726 mm" },
    { name: "Net weight", value: "29.1kg" },
    { name: "Gross weight", value: "32.1kg" },
  ]
downloads: [
    { title: "Hi-res photo", url: "", icon: "/images/jpg.gif" },
    {
      title: "Manual",
      url: "/download/syrincs_live_close15s_manual.pdf",
      icon: "/images/pdf.gif",
    },
    { title: "Dimensional drawing", url: "", icon: "/images/pdf.gif" },
    # { title: "Software", url: "", icon: "/images/unknown.gif" },
  ]
# | Specification parameters                  |                                                                            |
# | ----------------------------------------- | -------------------------------------------------------------------------- |
# | Box                                       | Painted Wooden Full Range Speaker                                          |
# | Unit composition                          | 1 x 15 "low-frequency unit 1 x 1.7" high-frequency driver                  |
# | Frequency division mode                   | Built in two-way frequency divider                                         |
# | Frequency response (-3dB)                 | 50Hz-18kHz                                                                 |
# | Frequency response (-10dB)                | 45Hz-20kHz                                                                 |
# | Rated power AES                           | 750W                                                                       |
# | Long term maximum power                   | 1500W                                                                      |
# | Short term maximum power                  | 3000W                                                                      |
# | Distortion 10% P                          | ≤5%                                                                        |
# | Sensitivity                               | Built in frequency divider 99 dB                                           |
# | Maximum sound pressure level pink noise   | Built in frequency divider 127dB/133dB (peak)                              |
# | Effective Sound Pressure Level Pink Noise | Built in Frequency Division 110dB/116dB (Peak)                             |
# | Impedance                                 | Built in frequency divider 8 Ω                                             |
# | Box                                       | 15mm+18mm laminated board                                                  |
# | Box surface treatment                     | Coal gray water-based sand surface paint spraying                          |
# | Iron mesh                                 | Electrostatic powder coating black fine sand matte, 1.2mm low carbon steel |
# | Connector                                 | 2 × NL4                                                                    |
# | Optional accessories                      | Lifting kit                                                                |
# | Dimensions (W × D × H)                    | 385 × 645 × 450 mm                                                         |
# | Packaging size                            | 465 × 573 × 726 mm                                                         |
# | Net weight                                | 29.1kg                                                                     |
# | Gross weight                              | 32.1kg                                                                     |
