title: MJ1239
ctitle: 3-way dual 12 inch waterproof full frequency linear array speaker
description: Frequency response:50Hz-20kHz (-3dB) | Rated power(RMS):LF:800W MF:400W  HF:150W | Sensitivity LF:100dB MF:110dB HF:113dB
image: /images/products/mj1239/mj1239-0.jpg
dimensional: /images/products/mj1239/mj1239-dimensions.png
images:
  [
    "/images/products/mj1239/mj1239-1.jpg",
    "/images/products/mj1239/mj1239-2.jpg",
    "/images/products/mj1239/mj1239-3.jpg",
    "/images/products/mj1239/mj1239-4.jpg",
    "/images/products/mj1239/mj1239-5.jpg",
    "/images/products/mj1239/mj1239-6.jpg",
    "/images/products/mj1239/mj1239-7.jpg",
    "/images/products/mj1239/mj1239-8.jpg",
  ]
category: speaker
slug: mj1239
date: 2024-04-02

features:
  [
    "The combination of dual 12 inch low-frequency and 1.75-inch high-frequency units provides high fidelity sound effects.",
    "The rated power is 2000W, and the maximum can reach 8000W, meeting the needs of various scenarios.",
    "15mm laminated board box with iron mesh, sturdy and durable.",
    "Equipped with NL4 connectors and lifting kits, it can flexibly adapt to various scenarios.",
    "Reasonable price, excellent performance, and value for money.",
  ]
content:
  Dual 12 inch low-frequency paired with dual coaxial mid to high frequency compression driver
  Accurate linear phase response brings perfect sound quality
  Vertical angle adjustment range:0 ° to 10 °, with an adjustment accuracy of 1 °, suitable for various venues
  Built in three-point hanging system, which can be conveniently and quickly hung or stacked for installation
  IP55 dustproof and waterproof certification

technicalspecification: [
    { name: "Frequency Response(-3db)", value: "55Hz-20kHz" },
    # { name: "Frequency Response(-10db)", value: "60Hz-20kHz" },
    { name: "Rated Power(RMS)", value: "LF: 800W MF:400W HF: 150W" },
    { name: "Total Power(MUSIC)", value: "LF: 1600W MF:800W HF:300W" },
    { name: "Total Power(PEAK)", value: "LF: 3200W MF:1600W HF:600W" },
    { name: "Max SPL @ 1m", value: "LF:129dB/135dB(PEAK)
        MF:136dB/142dB(PEAK)
        HF:134dB/140dB(PEAK)" },
    {
      name: "Dispersion (H x V)",
      value: "Horizontal 100 °, vertically 0-10°(adjustable)",
    },
    { name: "Sensitivity 1W @ 1m", value: "LF:100dB MF:110dB HF:113dB" },
    { name: "Nominal Impedance (Ohm)", value: "LF:4 Ω MF:8 Ω HF:16 Ω" },
    # { name: "Crossover Frequencies", value: "2.3kHz" },
    # { name: "Distortion 10% P", value: "≤5%" },
  ]

physicalspecification:
  [
    { name: "Box", value: "Dual 12 inch Waterproof Linear Array Speaker" },
    { name: "Woofer", value: "2 × 12 inch imported low frequency unit" },
    { name: "MF unit", value: "4 × 6 inch imported mid frequency unit" },
    {
      name: "Compression driver",
      value: "3 x 44 core inlet compression driver",
    },
    {
      name: "Frequency division mode",
      value: "External two division：200Hz-250Hz",
    },
    { name: "", value: "External tri-division：LF:200Hz-250Hz
        HF:2.5kHz-3.5kHz" },
    { name: "Cabinet/Case Material", value: "Import laminate board" },
    { name: "Box surface treatment", value: "Black polyimide spray" },
    { name: "Grille", value: "Black powder spraying" },
    { name: "Connector", value: "2 x NL4" },
    { name: "Optional Accessories", value: "Lifting kit" },
    { name: "Dimensions(W x D x H)", value: "1100 × 659 × 452mm" },
    { name: "Package Dimensions(W x D x H):", value: "1220 × 740 × 530mm" },
    { name: "Net weight", value: "56.5kg" },
    { name: "Gross weight", value: "62kg" },
  ]
downloads: [
    {
      title: "Hi-res photo",
      url: "/images/products/mj1239/mj1239-0.jpg",
      icon: "/images/jpg.gif",
    },
    {
      title: "Manual",
      url: "/download/syrincs_mj1239_manual.pdf",
      icon: "/images/pdf.gif",
    },
    # { title: "Dimensional drawing", url: "", icon: "/images/pdf.gif" },
    # { title: "Software", url: "", icon: "/images/unknown.gif" },
  ]
# | Specification parameters         |                                                                                                               |
# | -------------------------------- | ------------------------------------------------------------------------------------------------------------- |
# | System Type                      | Dual 12 inch Waterproof Linear Array Speaker System                                                           |
# | System composition               | 2 × T100-44 coaxial mid high frequency unit 2 × 12 "neodymium iron boron internal magnetic low-frequency unit |
# | Frequency response               | 55Hz-19kHz (± 3dB)                                                                                            |
# | Rated power                      | LF: 600W HF: 2000W                                                                                            |
# | Sensitivity                      | LF: 108dB HF: 114dB                                                                                           |
# | Maximum SPL                      | LF: 137dB HF: 143dB                                                                                           |
# | Rated impedance                  | 4 Ω                                                                                                           |
# | Directionality                   | Horizontal 100 °, vertically adjustable                                                                       |
# | Box                              | 18mm laminated board                                                                                          |
# | Box surface treatment            | Black polyurethane spray coating                                                                              |
# | Mesh                             | Black plastic powder coating, 6mm steel orifice plate                                                         |
# | Connector                        | 2 × NL4                                                                                                       |
# | Dimensions (W × D × H)           | 810 × 354 × 490mm                                                                                             |
# | Packaging dimensions (W × D × H) | 935 × 455 × 590mm                                                                                             |
# | Net weight                       | 48kg                                                                                                          |
# | Gross weight                     | 53kg                                                                                                          |
