---
title: WM3
ctitle: UHF wireless microphone
description: Streamlined appearance design, user-friendly interface, beautiful and elegant; High definition TBM LCD display screen, intuitive and clear; Adopting PLL dual channel phase-locked loop design, the old code locks the self selected channel function.
image: /images/products/wm3/wm3-0.jpg
dimensional:
images:
  [
    "/images/products/wm3/wm3-1.jpg",
    "/images/products/wm3/wm3-2.jpg",
    "/images/products/wm3/wm3-3.jpg",
    "/images/products/wm3/wm3-4.jpg",
  ]
category: microphone
slug: wm3
language: en
date: 2024-09-19

features: [
    "Streamlined appearance design, user-friendly interface, beautiful and elegant;
    ",
    "High definition TBM LCD display screen, intuitive and clear;
    ",
    "Adopting PLL dual channel phase-locked loop design, the old code locks the self selected channel function;
    ",
    "The sound curve has been carefully tuned, resulting in a warm and transparent sound;
    ",
    "Lockable control function selection, adjustable wireless gain connection function;
    ",
    "Adopting high-performance audio processing chips and ultra-low distortion sound processing circuit design;
    ",
    "Ultra high frequency dynamic compression splitting technology automatically splits and loads high and low frequencies Show better dynamic performance.
    ",
    "Brand new power regulation with 2-level power regulation.",
  ]
content:

technicalspecification:
  [
    { name: " System specifications", value: "" },
    { name: "Frequency range", value: "640-690MHz" },
    { name: "Total number of channels", value: "200CH" },
    { name: "Effective usage distance", value: "≈ 50m" },
    { name: "Frequency Interval", value: "250KHz" },
    { name: "Frequency Width", value: "50MHz " },
    { name: "Frequency module", value: "25 sets" },
    {
      name: "Frequency oscillation mode",
      value: "PLL phase locked frequency synthesis",
    },
  ]

physicalspecification:
  [
    { name: "Receiver       ", value: "      " },
    { name: "Signal to noise ratio", value: "≥ 50dB" },
    { name: "Frequency stability", value: " ± 5KHz" },
    {
      name: "Reception method",
      value: "CPU controlled signal selection+pilot identification reception",
    },
    { name: "Mute Lock Loop Circuit ", value: "" },
    { name: "Display mode   ", value: "LCD" },
    { name: "Power Supply   ", value: "12V DC, 1250mA" },
    {
      name: "Audio output interface",
      value: " 2 XLR Balanced Socket+Unbalance TRS 6.3mm Socket",
    },
  ]

downloads: [
    {
      title: "Hi-res photo",
      url: "/images/products/wm3/wm3-0.jpg",
      icon: "/images/jpg.gif",
    },
    {
      title: "Manual",
      url: "/download/Syrincs_wm3_manual.pdf",
      icon: "/images/pdf.gif",
    },
    # { title: "Dimensional drawing", url: "", icon: "/images/pdf.gif" },
    # { title: "Software", url: "", icon: "/images/unknown.gif" },
  ]
# | Specification parameters   |                                                                |
# | -------------------------- | -------------------------------------------------------------- |
# | System specifications      |                                                                |
# | Frequency range            | 640-690MHz                                                     |
# | Total number of channels   | 200CH                                                          |
# | Effective usage distance   | ≈ 50m                                                          |
# | Frequency Interval         | 250KHz                                                         |
# | Frequency Width            | 50MHz                                                          |
# | Frequency module           | 25 sets                                                        |
# | Frequency oscillation mode | PLL phase locked frequency synthesis                           |
# | Receiver                   |                                                                |
# | Signal to noise ratio      | ≥ 50dB                                                         |
# | Frequency stability        | ± 5KHz                                                         |
# | Reception method           | CPU controlled signal selection+pilot identification reception |
# | Mute Lock Loop Circuit     |
# | Display mode               | LCD                                                            |
# | Power Supply               | 12V DC, 1250mA                                                 |
# | Audio output interface     | 2 XLR Balanced Socket+Unbalance TRS 6.3mm Socket               |
