title: GP820
ctitle: Power controller
description: GP820 is a professional power timing distributor that can divide the input main power into eight power outputs, and can sequentially turn on and off each power supply in chronological order, effectively reducing the impact on the system. It is particularly suitable for use in large-scale audio engineering. ​
image: /images/products/gp820/gp820-0.jpg
dimensional:
images:
  ["/images/products/gp820/gp820-1.jpg", "/images/products/gp820/gp820-2.jpg"]
category: electronics
slug: gp820
language: en
date: 2024-08-01

features:
  [
    "One main circuit input and eight controlled power outputs.",
    "Internal microprocessor control, capable of sequential startup and reverse shutdown, and can be used in cascade with multiple units",
    "Each channel has LED indicators for on/off, which is clear at a glance.",
    "Equipped with BYPASS switch and independent control switch for each channel. Flexible to use.",
    "There is a USB 5V charging interface on the panel.",
    "Compact and sturdy.",
  ]
content: GP820 is a professional power timing distributor that can divide the input main power into eight power outputs, and can sequentially turn on and off each power supply in chronological order, effectively reducing the impact on the system. It is particularly suitable for use in large-scale audio engineering. ​

technicalspecification:
  [
    { name: "Maximum input power of the whole machine  ", value: " 16KW" },
    { name: "Maximum output power of each power channel", value: " 2KW " },
    { name: "Delay on/off time", value: " 1 second   " },
    { name: "Cascade control", value: "Yes " },
    { name: "BYPASS function ", value: "Yes " },
    { name: "ALL OFF function ", value: " Yes " },
  ]

physicalspecification:
  [
    { name: "Dimensions (W×D×H) ", value: "483 × 291 × 88mm" },
    { name: "Packaging size (W×D×H)", value: "526 × 369 × 145mm" },
    { name: "Net weight (kg/Pcs)  ", value: "5.7kg" },
    { name: "Total weight (kg/Pcs)", value: "7.6kg" },
  ]

downloads: [
    {
      title: "Hi-res photo",
      url: "/images/products/gp820/gp820-0.jpg",
      icon: "/images/jpg.gif",
    },
    {
      title: "Manual",
      url: "/download/syrincs_gp820_manual.pdf",
      icon: "/images/pdf.gif",
    },
    # { title: "Dimensional drawing", url: "", icon: "/images/pdf.gif" },
    # { title: "Software", url: "", icon: "/images/unknown.gif" },
  ]
# | Specification parameters                   |                  |
# | ------------------------------------------ | ---------------- |
# | Maximum input power of the whole machine   | 16KW             |
# | Maximum output power of each power channel | 2KW              |
# | Delay on/off time                          | 1 second         |
# | Cascade control                            | Yes              |
# | BYPASS function                            | Yes              |
# | ALL OFF function                           | Yes              |
# | Dimensions (W × D × H)                     | 484 × 222 × 88mm |
# | Packaging size (W × D × H)                 | 555 × 310 × 78mm |
# | Net weight (kg/Pcs)                        | 5kg              |
# | Total weight (kg/Pcs)                      | 6kg              |
