title: D MATCH2.6
ctitle: 数字处理器
description: 本设备将两路模拟输入音频信号数字化，并提供音频处理及音箱管理功能，非常适合中小型扩声场所的音质改善，并可在集中控制室监控系统的工作状态。
image: /images/products/dmatch2-6/dmatch2-6-0.jpg
dimensional:
images:
  [
    "/images/products/dmatch2-6/dmatch2-6-1.jpg",
    "/images/products/dmatch2-6/dmatch2-6-2.jpg",
  ]
category: processor
slug: dmatch2-6
language: zh
date: 2024-06-04

features:
  [
    "输入5段参量均衡、输出7段参量均衡",
    "每通道最大延时4000ms",
    "灵活的信号路由功能，任意输入均可路由至任意输出",
    "40组预置位存储空间",
    "多个控制接口（一个USB，一个RS232，一个RS485）",
    "图形控制软件",
  ]
content:
  D MATCH 2.6是一款数字音频处理器。该设备将两路模拟输入音频信号数字化，并提供音频处理和扬声器管理功能，非常适合中小型扩声场所的音质改善。它还可以在集中控制室监控系统的工作状态。通过在PC上安装系统控制软件，可以监控和管理RS-485控制总线上多达50台设备，轻松应对大型复杂应用。

  面板具有输入和输出电平动态裕度指示器，可以显示每个输出通道（音源、超低频、低频、中频和高频）的配置信息。数字显示屏显示设备地址代码或当前用户程序编号，可以使用面板上的触摸按钮设置地址代码或调用用户程序。该设备可以灵活地将两路输入信号分配到六路输出，配置为三路立体声或最多六路单声道分频器。

  两路输入信号可以灵活地分配到六路输出，配置为三路立体声或最多六路单声道分频器。此外，它还包括延迟、压缩/限制器、参数均衡器或图形均衡器等功能，因此该设备非常适合在扩声场所改善音质的应用。

technicalspecification: [
    { name: "频率响应", value: "20Hz~20KHz, ± 3dB" },
    { name: "信噪比", value: "≥90dB (typical value)" },
    { name: "总谐波失真+噪声", value: "THD+N＜0.006%" },
    # { name: "Other", value: "" },
    { name: "功耗", value: "＜20W" },
  ]

physicalspecification: [
    { name: "模拟输入", value: "" },
    {
      name: "连接器",
      value: "XLR-3 input socket (IN1 and IN2) 6.35 balanced input socket (BGM input)",
    },
    { name: "输入阻抗", value: "≥10k Ω" },
    # { name: "Reference level", value: "+4dBu" },
    { name: "最大输入电平", value: "≥ +20dBu（THD+N≤0.1%）" },
    {
      name: "A/D转换器",
      value: "> 64kHz, 24-bit Σ-Δ, 128-倍超级采样，线性相位",
    },
    # { name: "Lifting Height", value: "100mm" },
    { name: "模拟输出", value: "" },
    { name: "连接器", value: "XLR 输出卡插座（6通道）" },
    { name: "输出阻抗", value: "47 Ω（要求负载阻抗大于等于600Ω） " },
    # { name: "Load impedance", value: "600 Ω " },
    # { name: "Reference level", value: "+4dBu" },
    { name: "最大输入电平", value: "≥+20dbu（THD+N≤0.1%）" },
    { name: "A/D转换器", value: "128 times oversampling>64kHz, 24 bit ∑ - Δ" },
    { name: "控制接口", value: "" },
    { name: "RS-485 连接器", value: "XLR input/output" },
    { name: "BGM切换控制", value: "接线端子/DC+24V-48V    " },
    { name: "LED 电平表", value: "-40- 20,- 10,- 6dBFS and OVER (过载)" },
  ]

downloads: [
    {
      title: "照片",
      url: "/images/products/dmatch2-6/dmatch2-6-0.jpg",
      icon: "/images/jpg.gif",
    },
    {
      title: "说明书",
      url: "/download/Syrincs_d_macth_manual.pdf",
      icon: "/images/pdf.gif",
    },
    # { title: "Dimensional drawing", url: "", icon: "/images/pdf.gif" },
    { title: "Software", url: "/soft/dmatch.rar", icon: "/images/unknown.gif" },
  ]
# | Specification parameters                    |                                                                         |
# | ------------------------------------------- | ----------------------------------------------------------------------- |
# | Audio characteristics (analog input/output) |                                                                         |
# | Frequency response                          | 20Hz~20KHz, ± 0.5dB                                                     |
# | Signal to noise ratio                       | 110dB (typical value)                                                   |
# | Total harmonic distortion                   | 0.006%                                                                  |
# | Analog input                                |                                                                         |
# | Connector                                   | XLR-3 input socket (IN1 and IN2) 6.35 balanced input socket (BGM input) |
# | Input impedance                             | 10k Ω                                                                   |
# | Reference level                             | +4dBu                                                                   |
# | Maximum input level                         | +20dBu                                                                  |
# | A/D converter                               | 64kHz, 24 bit ∑ - Δ, 128 times oversampling, linear phase               |
# | Analog output                               |                                                                         |
# | Connector                                   | XLR-MALE output XLR-MALE socket (six channels)                          |
# | Output impedance                            | 47 Ω                                                                    |
# | Load impedance                              | 600 Ω                                                                   |
# | Reference level                             | +4dBu                                                                   |
# | Maximum input level                         | +20dBu                                                                  |
# | A/D converter                               | 128 times oversampling>64kHz, 24 bit ∑ - Δ                              |
# | Control interface                           |                                                                         |
# | RS-485 connector                            | XLR input/output                                                        |
# | BGM switching control                       | wiring terminal/DC+24V-48V                                              |
# | LED level meter                             | -40- 20,- 10,- 6dBFS and OVER (overload)                                |
# | Other                                       |                                                                         |
# | Power consumption                           | 18W                                                                     |
